wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_ADIPOGen_Adiponectin.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_Astle_et_al_2016_Eosinophil_counts.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_Astle_et_al_2016_Granulocyte_count.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_Astle_et_al_2016_High_light_scatter_reticulocyte_count.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_Astle_et_al_2016_Lymphocyte_counts.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_Astle_et_al_2016_Monocyte_count.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_Astle_et_al_2016_Myeloid_white_cell_count.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_Astle_et_al_2016_Neutrophil_count.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_Astle_et_al_2016_Platelet_count.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_Astle_et_al_2016_Red_blood_cell_count.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_Astle_et_al_2016_Reticulocyte_count.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_Astle_et_al_2016_Sum_basophil_neutrophil_counts.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_Astle_et_al_2016_Sum_eosinophil_basophil_counts.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_Astle_et_al_2016_Sum_neutrophil_eosinophil_counts.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_Astle_et_al_2016_White_blood_cell_count.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_BCAC_ER_negative_BreastCancer_EUR.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_BCAC_ER_positive_BreastCancer_EUR.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_BCAC_Overall_BreastCancer_EUR.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_CARDIoGRAM_C4D_CAD_ADDITIVE.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_CKDGen_Chronic_Kidney_Disease.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_CNCR_Insomnia_all.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_DIAGRAM_T2D_TRANS_ETHNIC.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_EAGLE_Eczema.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_EGG_BL.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_EGG_BMI_HapMapImputed.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_EGG_BW3_EUR.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_EGG_Pubertal_growth_10F.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_EGG_Pubertal_growth_12M.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_ENIGMA_Intracraneal_Volume.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_GABRIEL_Asthma.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_GEFOS_Forearm.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_GIANT_2015_BMI_EUR.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_GIANT_2017_BMI_Active_EUR.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_GIANT_HEIGHT.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_GIANT_HIP_Combined_EUR.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_GIANT_WC_Combined_EUR.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_GIANT_WHR_Combined_EUR.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_GLGC_Mc_HDL.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_GLGC_Mc_LDL.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_GLGC_Mc_TG.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_GPC-NEO-NEUROTICISM.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_HRGene_HeartRate.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_IBD.EUR.Crohns_Disease.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_IBD.EUR.Inflammatory_Bowel_Disease.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_IBD.EUR.Ulcerative_Colitis.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_ICBP_DiastolicPressure.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_ICBP_SystolicPressure.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_IGAP_Alzheimer.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_ILAE_Genetic_generalised_epilepsy.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_IMMUNOBASE_Celiac_disease_hg19.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_IMMUNOBASE_Multiple_sclerosis_hg19.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_IMMUNOBASE_Systemic_lupus_erythematosus_hg19.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_ISGC_Malik_2016_METASTROKE_all_strokes.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_Jones_et_al_2016_Chronotype.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_Jones_et_al_2016_SleepDuration.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_MAGIC_FastingGlucose.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_MAGIC_ln_FastingInsulin.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_MAGNETIC_CH2.DB.ratio.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_MAGNETIC_HDL.C.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_MAGNETIC_IDL.TG.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_MAGNETIC_LDL.C.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_PGC_ADHD_EUR_2017.txt.gz 
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_PGC_ASD_2017_CEU.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_pgc.scz2.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_RA_OKADA_TRANS_ETHNIC.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_SSGAC_Depressive_Symptoms.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_SSGAC_Education_Years_Pooled.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_TAGC_Asthma_EUR.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_tag.evrsmk.tbl.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_1160_Sleep_duration.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_1180_Morning_or_evening_person_chronotype.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_1200_Sleeplessness_or_insomnia.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_1807_Fathers_age_at_death.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20002_1065_self_reported_hypertension.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20002_1094_self_reported_deep_venous_thrombosis_dvt.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20002_1111_self_reported_asthma.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20002_1154_self_reported_irritable_bowel_syndrome.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20002_1222_self_reported_type_1_diabetes.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20002_1223_self_reported_type_2_diabetes.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20002_1225_self_reported_hyperthyroidism_or_thyrotoxicosis.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20002_1226_self_reported_hypothyroidism_or_myxoedema.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20002_1243_self_reported_psychological_or_psychiatric_problem.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20002_1261_self_reported_multiple_sclerosis.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20002_1262_self_reported_parkinsons_disease.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20002_1265_self_reported_migraine.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20002_1289_self_reported_schizophrenia.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20002_1309_self_reported_osteoporosis.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20002_1313_self_reported_ankylosing_spondylitis.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20002_1452_self_reported_eczema_or_dermatitis.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20002_1453_self_reported_psoriasis.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20002_1461_self_reported_inflammatory_bowel_disease.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20002_1462_self_reported_crohns_disease.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20002_1463_self_reported_ulcerative_colitis.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20002_1464_self_reported_rheumatoid_arthritis.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20002_1466_self_reported_gout.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20002_1473_self_reported_high_cholesterol.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20002_1616_self_reported_insomnia.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20016_Fluid_intelligence_score.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20022_Birth_weight.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_20127_Neuroticism_score.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_21001_Body_mass_index_BMI.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_23099_Body_fat_percentage.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_2395_2_Hair_or_balding_pattern_Pattern_2.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_2395_3_Hair_or_balding_pattern_Pattern_3.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_2395_4_Hair_or_balding_pattern_Pattern_4.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_3526_Mothers_age_at_death.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_50_Standing_height.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_6150_1_Vascular_or_heart_problems_diagnosed_by_doctor_Heart_attack.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_6152_5_diagnosed_by_doctor_Blood_clot_in_the_leg_DVT.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_6152_7_diagnosed_by_doctor_Blood_clot_in_the_lung.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_6152_8_diagnosed_by_doctor_Asthma.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_6152_9_diagnosed_by_doctor_Hayfever_allergic_rhinitis_or_eczema.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_G40_Diagnoses_main_ICD10_G40_Epilepsy.txt.gz
wget https://storage.googleapis.com/gtex-gwas-share/gwas-imputed/processed_summary_imputation/imputed_UKB_G43_Diagnoses_main_ICD10_G43_Migraine.txt.gz

