# Compare nominal P-values between my eGenes generated by following gtex-eqtl-pipeline.sh and GTEx v8 all pairs

import gzip
import os

mypairs_file="/mnt/lab_data/montgomery/nicolerg/gtex-eqtl/Whole_Blood.egenes.txt.gz"
allpairs_file="/mnt/lab_data/montgomery/shared/datasets/gtex/GTEx_Analysis_2017-06-05_v8/eqtl/GTEx_Analysis_v8_eQTL_all_associations/Whole_Blood.allpairs.txt.gz"
output_file="/users/nicolerg/gtex-admix/allpairs_overlap_v8.tsv"
genelist="/users/nicolerg/gtex-admix/genelist.txt"
#egenes_overlap="/users/nicolerg/gtex-admix/egenes_overlap_v8.tsv"
#gtex_egenes="/mnt/lab_data/montgomery/shared/datasets/gtex/GTEx_Analysis_2017-06-05_v8/eqtl/GTEx_Analysis_v8_eQTL/Whole_Blood.v8.egenes.txt.gz"

genedict={}
pdict={}
genematch={}
varmatch={}
gtex_varmatch={}
qdict={}

with gzip.open(mypairs_file,'r') as mypairs:   
    next(mypairs)
    for line in mypairs:
        line = line.strip().split('\t')
        genedict[line[0]] = line[5] # key=gene_id, val=variant_id
        varmatch[line[5]] = 0
        genematch[line[0]] = 0
        pdict[line[0]] = line[11] # key=gene_id, val=pval_nominal
        qdict[line[0]] = line[16]

# gtex_genedict={}
# gtex_pdict={}

# with gzip.open(gtex_egenes,'r') as gtexpairs:   
#     next(gtexpairs)
#     for line in gtexpairs:
#         line = line.strip().split('\t')
#         gtex_genedict[line[0]] = line[11] # key=gene_id, val=variant_id
#         gtex_pdict[line[0]] = line[23] # key=gene_id, val=pval_nominal
#         gtex_varmatch[line[11]] = 1

with open(output_file, 'w') as outfile:
	outfile.write("gene_id\tvariant_id\tmy_pval_nominal\tgtex_pval_nominal\n")
	#print('Comparing GTEx All Pairs to my eGenes...')
	with gzip.open(allpairs_file,'r') as allpairs:
		next(allpairs)
		for line in allpairs:
			line = line.strip().split('\t')
			if line[0] in genedict and genedict[line[0]] == line[1]:
				outfile.write(line[0]+"\t"+line[1]+"\t"+pdict[line[0]]+"\t"+line[6]+"\n")
			if line[0] in genematch:
				genematch[line[0]] = 1
			if line[1] in varmatch:
				varmatch[line[1]] = 1

totalvar = len(varmatch)
totalgene = len(genematch)
varhit = 0
genehit = 0

with open(genelist, 'w') as gene:
	for key in genematch:
		if genematch[key] == 1:
			genehit += 1
		else:
			gene.write(str(key)+"\n")

# print('Found '+str(varhit)+' out of my '+str(totalvar)+' eGene variants in GTEx all pairs.')
# print('Found '+str(genehit)+' out of my '+str(totalgene)+' eGene genes in GTEx all pairs.')

# # iterate through GTEx eGenes to find agreement
# # gene DNE
# nogene_count = 0
# # variant DNE
# novar_count = 0
# # pair DNA
# nopair_count = 0
# # both gene and variant exist, but they're not paired in GTEx
# diffpair_count = 0
# match_count = 0

# with open(egenes_overlap, 'w') as overlap:
# 	overlap.write('gene_id\tvariant_id\tmy_pval_nominal\tgtex_pval_nominal\n')
# 	print('')
# 	print('Comparing GTEx eGenes to my eGenes...')
# 	with gzip.open(mypairs_file,'r') as mypairs:   
# 	    next(mypairs)
# 	    for line in mypairs:
# 			line = line.strip().split('\t')
# 			if line[0] in gtex_genedict:
# 				if line[5] == gtex_genedict[line[0]]:
# 					match_count += 1
# 					overlap.write(line[0]+'\t'+line[5]+'\t'+line[11]+'\t'+gtex_pdict[line[0]]+'\n') # match
# 				else:
# 					if line[5] in gtex_varmatch:
# 						diffpair_count += 1
# 					else:
# 						novar_count += 1
# 					overlap.write(line[0]+'\t'+line[5]+'\t'+line[11]+'\t\n') # no match
# 			else:
# 				nogene_count += 1
# 				nopair_count += 1
# 				overlap.write(line[0]+'\t'+line[5]+'\t'+line[11]+'\t\n') # no match

# print("Number of eGenes in GTEx: " + str(len(gtex_genedict)))
# print("Number of eGenes in my version: " + str(len(genedict)))
# print('')
# print("Number of genes not included in GTEx eGenes: " + str(nogene_count))
# print("Number of variants not included in GTEx eGenes: " + str(novar_count))
# print("Number of mis-pairs in GTEx eGenes: " + str(diffpair_count))
# print("Number of matching eGenes: " + str(match_count))

# plot outputs with pval_overlap.R
